### ISSUE TITLE
The sdwebui-forge can't use asymmetric-tiling

### ISSUE THREAD

**Issue by storyskya** [tjm35/asymmetric-tiling-sd-webui#16]
Hello friend, the new version forge of sd-webui cannot use asymmetric controllers, can you upgrade it? Thanks a million

*** Error running postprocess: D:\forgeUI-N\webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py
    Traceback (most recent call last):
      File "D:\forgeUI-N\webui\modules\scripts.py", line 838, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\forgeUI-N\webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py", line 56, in postprocess
        self.__restoreConv2DMethods()
      File "D:\forgeUI-N\webui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py", line 74, in __restoreConv2DMethods
        for layer in modules.sd_hijack.model_hijack.layers:
    TypeError: 'NoneType' object is not iterable

**Comment by ImpossibleAd436** [comment]
I am having the same issue

**Comment by tjm35** [comment]
This extension is built against [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and prioritises working correctly with it. From what I can tell the [stable-diffusion-webui-forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) project has [completely replaced the hijack code this extension is built on](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/4337710c4a78765aa436208747b5d9e417f00610), so to make this extension work on that project would likely require a complete rewrite that then would no longer work on stable-diffusion-webui.

If someone wants to fork this project and rewrite it to work with stable-diffusion-webui-forge, of course they're welcome to do so (that's why I released it as CC0 after all), but this project only aims to support stable-diffusion-webui so this issue is a "won't fix".

**Comment by WyvernDryke** [comment]
I love this extension so much!  I miss it :(  Please can someone get it to work with Webui Forge?
