### ISSUE TITLE
Support for Highres-Fix please

### ISSUE THREAD

**Issue by GeorgLegato** [tjm35/asymmetric-tiling-sd-webui#9]
Hi, I use everyday your fabulous X-Tiling feature for 360-panoramas.
It  would be great, if your Tiling would apply in the Highres-fix-Step as well.
Hope it can be done without too much effort

here you see a seam due to Highresfix on and X-Tiling does not apply anymore

![image](https://user-images.githubusercontent.com/7210708/230732664-af9fa311-e7e2-4ccb-841f-70433c5fb3d1.png)

**Comment by tjm35** [comment]
Hi,

 I've confirmed that asymmetric tiling applies to both phases of the highres-fix generation (at least on auto1111 version a9fed7c, that I'm testing on).

 I think the problem that you're seeing is most likely because the _upscaler_ you're using (in this case R-ESRGAN) doesn't preserve tiling, so it adds a seam. The highres-fix-step will try to fix this, but 7 steps at 0.5 denoising isn't going to be enough for it to fix a relatively large discontinuity like this.

 My suggestion would be to either use an upscaler that will preserve tiling (I think "Latent" should, at least better than ESRGAN does?), or use more highres steps with a larger denoising strength so the generation has more opportunity to fix the problem.

 Thanks.

**Comment by j2l** [comment]
Hello all,
That would be great to have a working 
> upscaler that will preserve tiling

For me hires > upscale x2 is far slower (and throws a nightmare) than extra > upscale x4
So a good upscaler, or asymmetric-tiling in extra would be perfect.

Thanks for asymmetric @tjm35 and panorama view @GeorgLegato 
It's perfect together!

**Comment by tjm35** [comment]
I'm afraid developing a wrapping upscaler would be far out of scope for this project; that will have to be a different project by someone more familiar with the internals of modern upscaling networks.

**Comment by j2l** [comment]
I totally understand @tjm35 
I was asking if you or someone else knows about a working upscaler, or a trick (like photoshop offset filter within the upscaler) to make it work.
